name: stafferscraper
dependencies:
- openssl=1.0.2h=1
- pip=8.1.2=py35_0
- python=3.5.0=1
- readline=6.2=2
- setuptools=23.0.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=3
- pip:
  - oauthlib==1.1.2
  - pyyaml==3.11
  - requests==2.10.0
  - requests-oauthlib==0.6.2
  - twython==3.4.0

