#!/usr/bin/env python3

import sys
from stafferscraper.twittersession import TwitterSession
from stafferscraper.config.loadconfig import load_config

if __name__ == "__main__":

    # Input arg handling
    userID = sys.argv[1]

    # Config
    configFileName = 'StafferScraper_config.yml'

    config     = load_config(configFileName)
    API_KEY    = config['API_KEY']
    API_SECRET = config['API_SECRET']

    # Login
    twitter = TwitterSession()
    twitter.login(API_KEY, API_SECRET)

    # Set userID to scrape
    twitter.setUserID(userID)

    latestTweet = twitter.getLatestTweet()

    print(latestTweet['text'])